### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/multi-store#26]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] sale_multi_store
- [ ] base_multi_store
- [ ] purchase_multi_store
- [ ] account_multi_store
- [ ] stock_multi_store
