### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/multi-store#4]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_multi_store
- [ ] base_multi_store
- [ ] purchase_multi_store
- [ ] sale_multi_store
- [ ] stock_multi_store
